version: '2'

services:
  match-service:
    container_name: matchservice
    build: .
    ports:
      - "8081:8081"
    links:
      - app-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://app-db:5432/matches
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
  app-db:
    container_name: app-db
    image: 'postgres:14-alpine'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=matches