version: '2'

services:
  match-service:
    container_name: matchservice
    build: .
    ports:
      - "8000:8000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/matches
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'postgres:14-alpine'
    container_name: db
    environment:
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= root